### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by stevewirts** [ghpabs/angular2-seed-project#53]
on windows 7 machine, I get this error when I run `gulp build serve`

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Liftoff.handleArguments (C:\Users\swirts\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\swirts\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:192:16)
    at module.exports (C:\Users\swirts\AppData\Roaming\npm\node_modules\gulp\node_modules\flagged-respawn\index.js:17:3)

looks like the gulpfile has ES6 spreads in it?

any guidance would be greatly appreciated.

**Comment by ghpabs** [comment]
Yup you can either use .concat() or install Node v5.x.

**Comment by stevewirts** [comment]
I loaded node v5.0.0, didn't seem to work. are you saying to use concat()
in gulpfile.js?

swirts@JC1WDETG97 ~/Projects/markdown
$ node -v
v5.0.0

swirts@JC1WDETG97 ~/Projects/markdown
$ npm -v
3.5.3

swirts@JC1WDETG97 ~/Projects/markdown
$ gulp build serve
[15:30:11] Using gulpfile H:\Projects\markdown\gulpfile.js
C:\Users\swirts\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at
C:\Users\swirts\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:19
    at doNTCallback0 (node.js:428:9)
    at process._tickDomainCallback (node.js:398:13)

**Comment by stevewirts** [comment]
Hi,
I think maybe this is just a different issue, the ... problem is gone now.
thanks

**Comment by ghpabs** [comment]
Cool, try installing Gulp again as you got new NPM/Node versions now.

**Comment by ghpabs** [comment]
I'm happy to reopen if you're still having problems.
