### ISSUE TITLE
Error when run gulp

### ISSUE THREAD

**Issue by leonardoblanco** [ghpabs/angular2-seed-project#57]
```
$ git clone https://github.com/ghpabs/angular2-seed-project.git && cd angular2-seed-project
$ nem install
$ gulp build serve

[10:18:03] Using gulpfile ~/angular2-seed-project/gulpfile.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
    at Function.Module.runMain (module.js:459:11)
    at startup (node.js:138:18)
    at node.js:974:3
```

**Comment by maxime1992** [comment]
Isn't it related to https://github.com/ghpabs/angular2-seed-project/issues/53 ?
What's your node version ?

**Comment by andymdswan** [comment]
I think this is actually the gulp-cli version. From memory its when you have a mismatch. Make sure you have version 4 of gulp and gulp-cli

**Comment by leonardoblanco** [comment]
Yes! I updated to the last stable version of gulp and I got this error. Now I installed the version 4 beta and it works properly!

Thales

**Comment by ghpabs** [comment]
Great - thanks guys.

**Comment by marcysutton** [comment]
I am still getting this error even with the version 4 beta. Here are my versions:
```
[20:25:40] CLI version 3.9.1
[20:25:40] Local version 4.0.0-alpha.2
```
I am super confused about gulp here. Which version(s) do I need?

**Comment by ghpabs** [comment]
Hi @marcysutton I'm afraid you have the wrong version installed globally. Here's how it should read:

```
➜ gulp -v
[14:09:20] CLI version 0.4.0
[14:09:20] Local version 4.0.0-alpha.2
```

See below how to install Gulp 4 globally: 

```
npm uninstall -g gulp
npm install -g "gulpjs/gulp-cli#4.0"
```

http://blog.reactandbethankful.com/posts/2015/05/01/how-to-install-gulp-4/

Let me know how it goes.

**Comment by marcysutton** [comment]
Ahh, it was because I'm in nvm version hell. Each project requires something different...I just had to use the right combination of node and gulp.

**Comment by klall** [comment]
I am running into this problem currently. 

In my environment I have:
20:53 $ gulp --version
[20:53:42] CLI version 3.9.1
[20:53:42] Local version 4.0.0-alpha.2

node --version
v6.4.0

npm --version
3.10.7

Note that I could not do:
20:54 $ npm install -g "gulpjs/gulp-cli#4.0"
npm ERR! git rev-list -n1 4.0: fatal: ambiguous argument '4.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 4.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 4.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 4.0: 

I just did npm install -g gulp. Somehow gulp --version thinks it is at 4.0.0-alpha.2 though. 

Also I am using nvm. I'm not sure if @marcysutton resolved something else related to nvm.

**Comment by klall** [comment]
npm start gives this message. I am on a Mac:

20:57 $ npm start

> angular2-seed-advanced@0.0.0 start /Users/kamlall/Box Sync/explore/angular2-seed-advanced
> gulp --version; gulp serve.dev --color --config-env dev

[20:57:11] CLI version 3.9.1
[20:57:11] Local version 4.0.0-alpha.2
[20:57:11] Working directory changed to ~/Box Sync/explore
[20:57:12] Loading /Users/kamlall/Box Sync/explore/gulp_tasks/browsersync.js
[20:57:12] Loading /Users/kamlall/Box Sync/explore/gulp_tasks/build.js
[20:57:12] Loading /Users/kamlall/Box Sync/explore/gulp_tasks/karma.js
[20:57:13] Loading /Users/kamlall/Box Sync/explore/gulp_tasks/misc.js
[20:57:13] Loading /Users/kamlall/Box Sync/explore/gulp_tasks/scripts.js
[20:57:13] Loading /Users/kamlall/Box Sync/explore/gulp_tasks/styles.js
[20:57:13] Loading /Users/kamlall/Box Sync/explore/gulp_tasks/systemjs.js
[20:57:13] Using gulpfile ~/Box Sync/explore/gulpfile.js
/Users/kamlall/.nvm/versions/node/v6.4.0/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /Users/kamlall/.nvm/versions/node/v6.4.0/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by klall** [comment]
The following worked for me:
https://github.com/pattern-lab/edition-node-gulp/wiki/Updating-to-Gulp-4
