### ISSUE TITLE
Fresh Clone, but Gulp Build not working

### ISSUE THREAD

**Issue by kambojankit** [ghpabs/angular2-seed-project#59]
Hey i did a fresh clone of your project, and ran npm install successfully.

I have gulp-cli#4.0 installed globally, but on executing 'gulp build serve', i get below error:

Error: 
` return gulp.src(['src/scripts/**/*.ts', ...paths.typings])`

```
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at execute (C:\Users\******\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^4.0.0-alpha.2\index.js:32:3)
    at Liftoff.handleArguments (C:\Users\******\AppData\Roaming\npm\node_modules\gulp-cli\index.js:150:63)
    at Liftoff.<anonymous> (C:\Users\*******\AppData\Roaming\npm\node_modules\gulp-cli\node_modules\liftoff\index.js:192:16)
```

**Comment by Wobbly-Wibbly** [comment]
This is new SpreadOperator in ECMAScript 6. 
http://es6-features.org/#SpreadOperator
You should update your NodeJS

**Comment by kambojankit** [comment]
Thanks for the input, it worked for me.

I missed it out initially, but a similar issue was logged as issue #57 and #53. (My Bad :( )

**Comment by ghpabs** [comment]
Cool I'm glad you managed to fix it. See README for all global dependencies. Cheers.
